# Store application setting variables and sensitive information here.
# Rename this file to "coins.yml" and make sure it's listed in your
# .gitignore for safety.

BLK:
   development: &base
      rpc_user: "blackcoinrpc"
      rpc_password: "rpc_password"
      rpc_host: "localhost"
      rpc_port: "15715"
      rpc_ssl: false
      wallet_password: "abc!"
      confirmations: 10

   test:
     <<: *base

   production:
      rpc_user: "blackcoinrpc"
      rpc_password: "rpc_password"
      rpc_host: "localhost"
      rpc_port: "15715"
      rpc_ssl: false
      wallet_password: "abc!"
      confirmations: 10
